name: latent_space_builder
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python=3.8
  - bokeh
  - jupyterlab
  - scikit-learn
  - h5py
  - pip
  - pip:
    - numpy==1.19.0
    - pyDiffMap
    - kora