package:
  name: latent-space-builder
  version: 0.0.1

source:
  path: .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scikit-learn
    - h5py

about:
  home: https://github.com/compSPI/LatentSpaceBuilder
